### ISSUE TITLE
Windows build can't run by default

### ISSUE THREAD

**Issue by ryanhartje** [ryanhartje/kpong#5]
When running the windows build, I get `The code execution cannot proceed because libwinpthread-1.dll was not found. Reinstalling the program may fix this problem.`

Seems like we need to advise the end user to install some GLFW package or something before this can run.

**Comment by ryanhartje** [comment]
Another action item is that the release for windows should have the `.exe` extension.

Missing DLL can be found here and placed in the same folder as the binary, however it seems like we have more errors after that. 

Latest: 
```
The application was unable to start correctly (0xc000007b).
Click OK to close the application.
```

**Comment by ryanhartje** [comment]
Here's the output from an mingw-w64 command line:
```
$ ./kpong-v0.1.1-windows
Encountered error when setting up kubernetes clientcmd: CreateFile C:\msys64\home\devoops/.kube/config: The system cannot find the file specified.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x1080d2f]

goroutine 1 [running, locked to thread]:
k8s.io/client-go/kubernetes/typed/core/v1.(*pods).List(0xc00020cd40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/devoops/go/pkg/mod/k8s.io/client-go@v0.17.0/kubernetes/typed/core/v1/pod.go:89 +0xcf
github.com/ryanhartje/kpong/pkg/kpong.GetRandomPod(0xc0002ae420, 0x0, 0x0, 0x1617a80, 0xc000293a40, 0x1111af7)
        C:/Users/devoops/go/src/github.com/ryanhartje/kpong/pkg/kpong/kubeclient.go:37 +0xb0
github.com/ryanhartje/kpong/pkg/kpong.Start(0x0, 0x0, 0x0, 0x0)
        C:/Users/devoops/go/src/github.com/ryanhartje/kpong/pkg/kpong/kpong.go:26 +0xbf
main.newRootCmd.func1(0xc000210b00, 0x1f2f608, 0x0, 0x0)
        C:/Users/devoops/go/src/github.com/ryanhartje/kpong/cmd/kpong/kpong.go:22 +0x58
github.com/spf13/cobra.(*Command).execute(0xc000210b00, 0xc00006c1c0, 0x0, 0x0, 0xc000210b00, 0xc00006c1c0)
        C:/Users/devoops/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2a4
github.com/spf13/cobra.(*Command).ExecuteC(0xc000210b00, 0x0, 0x0, 0xc000210b00)
        C:/Users/devoops/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/devoops/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        C:/Users/devoops/go/src/github.com/ryanhartje/kpong/cmd/kpong/kpong.go:37 +0x81
INFO: Initializing raylib 3.0
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1920 x 1080
INFO:     > Render size:  1024 x 800
INFO:     > Screen size:  1024 x 800
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: OpenGL 3.3 Core profile supported
INFO: GL: OpenGL device information:
INFO:     > Vendor:   NVIDIA Corporation
INFO:     > Renderer: GeForce GTX 1070/PCIe/SSE2
INFO:     > Version:  3.3.0 NVIDIA 445.87
INFO:     > GLSL:     3.30 NVIDIA via Cg compiler
INFO: GL: Supported extensions count: 388
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: GL: Anisotropic textures filtering supported (max: 16X)
INFO: GL: Mirror clamp wrap texture mode supported
INFO: TEXTURE: [ID 1] Texture created successfully (1x1 - 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Compiled successfully
INFO: SHADER: [ID 2] Compiled successfully
INFO: SHADER: [ID 3] Program loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Internal vertex buffers initialized successfully in RAM (CPU)
INFO: RLGL: Internal vertex buffers uploaded successfully to VRAM (GPU)
INFO: RLGL: Default state initialized successfully
INFO: TEXTURE: [ID 2] Texture created successfully (128x128 - 1 mipmaps)
INFO: FONT: Default font loaded successfully
INFO: AUDIO: Device initialized successfully
INFO:     > Backend:      miniaudio / WASAPI
INFO:     > Format:       32-bit IEEE Floating Point -> 32-bit IEEE Floating Point
INFO:     > Channels:     2 -> 2
INFO:     > Sample rate:  44100 -> 44100
INFO:     > Periods size: 1320
INFO: AUDIO: Multichannel pool size: 16
INFO: TIMER: Target time per frame: 16.667 milliseconds
```
